title: Catherine Delannoy
logo: /cropped_image.png
description: |
  <br><br>
  <a href="https://www.linkedin.com/in/catherinedelannoy/">View My LinkedIn Profile</a> 
show_downloads: true
theme: jekyll-theme-minimal
